villagereach/selv-v3-ui

src/stock-choose-date-modal/choose-date-modal.controller.js
src/stock-physical-inventory-draft/physical-inventory-draft.controller.js

Fixed error while submitting physical inventory, error no longer occurs

SELV3-508: Fix error when submitting physical inventory

---

src/admin-dhis2/admin-dhis2.service.js
src/admin-dhis2/admin-dhis2.wrapper.jsx
src/admin-dhis2/components/AdminDhis2ServersForm/AdminDhis2ServersForm.jsx
src/admin-dhis2/components/AdminDhis2ServersPage/AdminDhis2ServersPage.jsx
src/admin-dhis2/components/AdminDhis2ServersPage/_admin-dhis2-servers-page.scss
src/admin-dhis2/components/Modal/Modal.jsx
src/admin-dhis2/components/Modal/_modal.scss

TICKET: https://openlmis.atlassian.net/browse/SELV3-554
Presentation of change:
Moreover I added toast after 'delete' operation.

SELV3-554: Create Add Server modal window (Frontend)

---

src/admin-dhis2/Routing.jsx
src/admin-dhis2/admin-dhis2.routes.js
src/admin-dhis2/components/AdminDhis2DatasetPage/AdminDhis2DatasetPage.jsx
src/admin-dhis2/components/AdminDhis2DatasetPage/index.jsx
src/admin-dhis2/components/AdminDhis2ServersPage/AdminDhis2ServersPage.jsx
src/admin-dhis2/components/Modal/_modal.scss

TICKET: https://openlmis.atlassian.net/browse/SELV3-557
Presentation of change
including resizing of 'modal'

SELV3-557: Create empty dataset page when user clicks View button next to any server

---

src/admin-dhis2/admin-dhis2.service.js
src/admin-dhis2/components/AdminDhis2DatasetPage/AdminDhis2DatasetPage.jsx
src/admin-dhis2/components/AdminDhis2ServersPage/AdminDhis2ServersPage.jsx

TICKET: https://openlmis.atlassian.net/browse/SELV3-558
Presentation of change:

SELV3-558: Create a dataset table on dataset page (Frontend)

---

src/admin-dhis2/components/AdminDhis2DatasetPage/AdminDhis2DatasetPage.jsx

Moved sync button to Server Datasets Table after change of requirements

SELV3-652:  Move Sync Button to table in Server Datasets view

---

src/shipment/shipment-repository-impl.js

changes done by me are between commented lines (starting with SELV3-666)

SELV3-666: Fix bug related to 'User cannot fulfill the order'

---

src/admin-supply-line-add/admin-supply-line-add.controller.js
src/admin-supply-line-add/admin-supply-line-add.module.js
src/admin-supply-line-add/admin-supply-line-add.routes.js
src/admin-supply-line-add/messages_en.json
src/admin-supply-line-add/supply-line-add.html
src/admin-supply-line-list/messages_en.json
src/admin-supply-line-list/supply-line-list.html

Ticket: https://openlmis.atlassian.net/browse/SELV3-475

SELV3-475: Add Supply Line

---

src/report/messages_en.json
src/report/report-list.controller.js
src/report/report-list.html

Ticket: https://openlmis.atlassian.net/browse/SELV3-695

SELV3-695: Modify reports page

---

src/admin-supply-line-add/messages_en.json
src/admin-supply-line-add/supply-line-add.html
src/admin-supply-line-list/messages_en.json
src/admin-supply-line-list/supply-line-list.html

ticket: https://openlmis.atlassian.net/browse/SELV3-475

SELV-475: changed the '+' from text to icon, it is balder

---

src/order-view/order-view.controller.js
src/order/messages_en.json
src/order/order-status.factory.js
src/order/order-statuses.constant.js

ticket: https://openlmis.atlassian.net/browse/SELV3-229

SELV-229: added missing translation and updated filter by status

---

src/report/messages_en.json
src/report/report-generate.controller.js
src/report/report-generate.html
src/report/report.module.js

JIRA task link: https://openlmis.atlassian.net/browse/SELVSUP-6

SELVSUP-6: Added datepicker & boolean checkbox to report options

---

src/admin-valid-destination-list/admin-valid-destination-list.module.js
src/admin-valid-destination-list/valid-destination-list.controller.js
src/admin-valid-destination-list/valid-destination-list.html
src/admin-valid-source-list/admin-valid-source-list.module.js
src/admin-valid-source-list/valid-source-list.controller.js
src/admin-valid-source-list/valid-source-list.html
src/order-view/order-view.controller.js
src/order-view/order-view.controller.spec.js
src/order-view/order-view.html
src/order-view/order-view.routes.js
src/requisition-approval/requisition-approval-list.controller.js
src/requisition-approval/requisition-approval-list.controller.spec.js
src/requisition-approval/requisition-approval-list.html
src/requisition-approval/requisition-approval.routes.js
src/requisition-approval/requisition-approval.routes.spec.js

https://openlmis.atlassian.net/browse/SELV3-718

SELV-718: updates to filters

---

src/openlmis-home/csp-generate.run.js
src/requisition-search/requisition-search.controller.spec.js
src/requisition/requisition-data-builder.spec.js

Selv logos was not displayed due to the CSP header. It had to be changed. 
Two files had wrong copyright header

Modified csp to display images and corrected copyright headers

---

src/requisition-approval/requisition-approval.routes.js
src/requisition-search/requisition-search.routes.js

resolving bug:  https://openlmis.atlassian.net/browse/SELV3-763

SELV3-763: disabled view and approve requisitions in offline mode

---

src/requisition-approval/requisition-approval-list.controller.js
src/requisition-initiate/requisition-initiate.controller.js
src/requisition-search/requisition-search.controller.js

resolving bug: https://openlmis.atlassian.net/browse/SELV3-761

SELV-761: navigating to view requisition works

---

src/requisition-product-grid/product-grid-cell.directive.js

SELV3-758:  Removed condition to edit totalReceivedQuantity column

SELV3-758:  Removed condition to edit totalReceivedQuantity column

---

src/order-view/messages_en.json
src/order-view/order-view.controller.js
src/order-view/order-view.html
src/order-view/order-view.routes.js

[SELV3-769](https://openlmis.atlassian.net/browse/SELV3-769)
Changes:
- Add possibility to sort orders (by date created property - asc, desc).
[SELV3-769]: https://openlmis.atlassian.net/browse/SELV3-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELV3-769: add order sorting

---

src/requisition-view-tab/requisition-view-tab.controller.js

resolving bug: https://openlmis.atlassian.net/browse/SELVSUP-36

SELVSUP-36: fixed editing column, Receibido

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.html

Task:
https://openlmis.atlassian.net/browse/SELVSUP-42

SELVUP-42: Added default reason for Issue and Receive

---

src/stock-adjustment-creation/adjustment-creation.controller.js
src/stock-adjustment-creation/adjustment-creation.controller.spec.js
src/stock-adjustment-creation/adjustment-creation.html
src/stock-adjustment-creation/adjustment-creation.routes.js
src/stock-issue-creation/issue-creation.routes.js
src/stock-receive-creation/receive-creation.routes.js

Changes:
- Moved reason download to routes, 
- reason comment always available for default reason

SELVSUP-42: Moved reason download to routes, reason comment always always available for default reason

---

CHANGELOG.md
src/report/messages_en.json
src/report/report-generate.controller.js
src/report/report-generate.html

[SELVSUP-17](https://openlmis.atlassian.net/browse/SELVSUP-17)
Changes:
- Use translations
- Format code
[SELVSUP-17]: https://openlmis.atlassian.net/browse/SELVSUP-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELVSUP-17: use translations rather than hardcoded values

---

CHANGELOG.md
src/shipment-view/shipment-view-line-item-factory.js
src/shipment-view/shipment-view-line-item-group.js
src/shipment-view/shipment-view-line-item.js
src/shipment-view/shipment-view.controller.js
src/shipment-view/shipment-view.html

Task:
https://openlmis.atlassian.net/browse/SELVSUP-14
Changes:
Recalculate input quantity to doses on Fulfill orders page

SELVSUP-14: Recalculate input quantity to doses
